export type Difficulty =
  | "Easy"
  | "Medium"
  | "Hard"
  | "Very Hard"
  | "Expert";

export type SpecialBubble = "bomb" | "rainbow" | "freeze" | "aim";

export interface LevelConfig {
  level: number;
  difficulty: Difficulty;
  colors: string[];
  descentInterval: number;
  randomColorChance: number;
  movingRows?: number[];
  movingAmplitude?: number;
  movingSpeed?: number;
  bonusTimer?: number;
  hasObstacles?: boolean;
  rainbowChance?: number;
  bombChance?: number;
  freezeChance?: number;
  aimChance?: number;
  pattern: "cluster" | "staggered" | "hourglass" | "maze" | "random" | "double";
  timeLimitSeconds?: number;
  doubleLayer?: boolean;
  aimGuideMultiplier?: number;
  endless?: boolean;
}

export const BUBBLE_COLORS: Record<
  string,
  { label: string; fill: string; border: string }
> = {
  red: { label: "Red", fill: "#ff5c5c", border: "#c21237" },
  blue: { label: "Blue", fill: "#4d9bff", border: "#1c5db6" },
  green: { label: "Green", fill: "#3ed598", border: "#187d51" },
  yellow: { label: "Yellow", fill: "#ffe177", border: "#c19a1a" },
  purple: { label: "Purple", fill: "#c77dff", border: "#6b2fab" },
  orange: { label: "Orange", fill: "#ff9a62", border: "#c4531d" },
  cyan: { label: "Cyan", fill: "#52e7ff", border: "#008aa3" },
  pink: { label: "Pink", fill: "#ff7dc8", border: "#c4338d" },
  gray: { label: "Gray", fill: "#8d95a6", border: "#5a5f6b" },
};

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    difficulty: "Easy",
    colors: ["red", "blue", "green"],
    descentInterval: 16000,
    randomColorChance: 0,
    pattern: "cluster",
    aimGuideMultiplier: 1.1,
  },
  {
    level: 2,
    difficulty: "Easy",
    colors: ["red", "blue", "green", "yellow"],
    descentInterval: 15000,
    randomColorChance: 0.02,
    pattern: "cluster",
    movingRows: [3],
    movingAmplitude: 12,
    movingSpeed: 0.6,
    aimGuideMultiplier: 1.1,
  },
  {
    level: 3,
    difficulty: "Easy",
    colors: ["red", "blue", "green", "yellow"],
    descentInterval: 14000,
    randomColorChance: 0.03,
    pattern: "staggered",
    movingRows: [2, 5],
    movingAmplitude: 16,
    movingSpeed: 0.8,
    aimGuideMultiplier: 1.05,
  },
  {
    level: 4,
    difficulty: "Medium",
    colors: ["red", "blue", "green", "yellow", "purple"],
    descentInterval: 12500,
    randomColorChance: 0.04,
    pattern: "hourglass",
    movingRows: [1, 4, 6],
    movingAmplitude: 18,
    movingSpeed: 0.95,
    aimGuideMultiplier: 1,
  },
  {
    level: 5,
    difficulty: "Medium",
    colors: ["red", "blue", "green", "yellow", "purple"],
    descentInterval: 12000,
    randomColorChance: 0.05,
    pattern: "cluster",
    movingRows: [2, 5, 7],
    movingAmplitude: 28,
    movingSpeed: 1.1,
    aimGuideMultiplier: 1,
  },
  {
    level: 6,
    difficulty: "Medium",
    colors: ["red", "blue", "green", "yellow", "purple"],
    descentInterval: 11000,
    randomColorChance: 0.08,
    pattern: "staggered",
    bonusTimer: 12,
    aimGuideMultiplier: 1,
  },
  {
    level: 7,
    difficulty: "Medium",
    colors: ["red", "blue", "green", "yellow", "purple", "orange"],
    descentInterval: 10500,
    randomColorChance: 0.09,
    pattern: "hourglass",
    bonusTimer: 10,
    freezeChance: 0.08,
    aimChance: 0.06,
    aimGuideMultiplier: 0.95,
  },
  {
    level: 8,
    difficulty: "Medium",
    colors: ["red", "blue", "green", "yellow", "purple", "orange"],
    descentInterval: 9500,
    randomColorChance: 0.1,
    pattern: "cluster",
    movingRows: [1, 3, 5, 7],
    movingAmplitude: 24,
    movingSpeed: 1.2,
    aimGuideMultiplier: 0.9,
  },
  {
    level: 9,
    difficulty: "Hard",
    colors: ["red", "blue", "green", "yellow", "purple", "orange"],
    descentInterval: 9000,
    randomColorChance: 0.12,
    pattern: "maze",
    hasObstacles: true,
    rainbowChance: 0.05,
    aimGuideMultiplier: 0.9,
  },
  {
    level: 10,
    difficulty: "Hard",
    colors: ["red", "blue", "green", "yellow", "purple", "orange"],
    descentInterval: 8500,
    randomColorChance: 0.13,
    pattern: "random",
    bombChance: 0.07,
    aimGuideMultiplier: 0.85,
  },
  {
    level: 11,
    difficulty: "Hard",
    colors: ["red", "blue", "green", "yellow", "purple", "orange", "cyan"],
    descentInterval: 8000,
    randomColorChance: 0.14,
    pattern: "hourglass",
    rainbowChance: 0.12,
    freezeChance: 0.1,
    aimChance: 0.08,
    aimGuideMultiplier: 0.85,
  },
  {
    level: 12,
    difficulty: "Hard",
    colors: ["red", "blue", "green", "yellow", "purple", "orange", "cyan"],
    descentInterval: 7400,
    randomColorChance: 0.15,
    pattern: "maze",
    movingRows: [0, 2, 4, 6, 8],
    movingAmplitude: 26,
    movingSpeed: 1.35,
    aimGuideMultiplier: 0.8,
  },
  {
    level: 13,
    difficulty: "Hard",
    colors: ["red", "blue", "green", "yellow", "purple", "orange", "cyan"],
    descentInterval: 7000,
    randomColorChance: 0.17,
    pattern: "staggered",
    movingRows: [1, 3, 5, 7],
    movingAmplitude: 42,
    movingSpeed: 1.4,
    aimGuideMultiplier: 0.75,
  },
  {
    level: 14,
    difficulty: "Hard",
    colors: ["red", "blue", "green", "yellow", "purple", "orange", "cyan"],
    descentInterval: 6500,
    randomColorChance: 0.18,
    pattern: "random",
    timeLimitSeconds: 150,
    aimGuideMultiplier: 0.7,
  },
  {
    level: 15,
    difficulty: "Hard",
    colors: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "cyan",
      "pink",
    ],
    descentInterval: 6000,
    randomColorChance: 0.2,
    pattern: "double",
    doubleLayer: true,
    bombChance: 0.12,
    aimGuideMultiplier: 0.7,
  },
  {
    level: 16,
    difficulty: "Very Hard",
    colors: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "cyan",
      "pink",
    ],
    descentInterval: 5600,
    randomColorChance: 0.22,
    pattern: "random",
    rainbowChance: 0.15,
    bombChance: 0.14,
    aimGuideMultiplier: 0.65,
  },
  {
    level: 17,
    difficulty: "Very Hard",
    colors: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "cyan",
      "pink",
    ],
    descentInterval: 5200,
    randomColorChance: 0.24,
    pattern: "maze",
    hasObstacles: true,
    freezeChance: 0.14,
    bombChance: 0.17,
    movingRows: [0, 2, 4, 6, 8, 10],
    movingAmplitude: 46,
    movingSpeed: 1.55,
    aimGuideMultiplier: 0.6,
  },
  {
    level: 18,
    difficulty: "Very Hard",
    colors: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "cyan",
      "pink",
    ],
    descentInterval: 4800,
    randomColorChance: 0.26,
    pattern: "staggered",
    rainbowChance: 0.18,
    bombChance: 0.18,
    freezeChance: 0.16,
    aimChance: 0.12,
    aimGuideMultiplier: 0.6,
  },
  {
    level: 19,
    difficulty: "Very Hard",
    colors: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "cyan",
      "pink",
    ],
    descentInterval: 4400,
    randomColorChance: 0.28,
    pattern: "random",
    aimGuideMultiplier: 0.35,
    rainbowChance: 0.22,
    bombChance: 0.2,
  },
  {
    level: 20,
    difficulty: "Expert",
    colors: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "cyan",
      "pink",
    ],
    descentInterval: 3800,
    randomColorChance: 0.3,
    pattern: "random",
    aimGuideMultiplier: 0.3,
    rainbowChance: 0.25,
    bombChance: 0.24,
    freezeChance: 0.22,
    endless: true,
  },
];
